[package]
name = "rust-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.16.1"
gobject-2-0-sys = "0.46.4"
gobject-sys = "0.16.3"
cairo = "0.0.4"
gio = "0.16.3"
pango = "0.16.3"
